FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

# Patch: avoid PostCSS export error
RUN npm install --no-save postcss@latest postcss-safe-parser@latest

COPY . .

ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


